# Generated by Django 4.1.4 on 2022-12-13 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapi', '0002_user_is_admin_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 20, 3, 32, 177848)),
        ),
    ]
